title: 'Theme Settings'
data:
  colours:
    -
      id: m561eno4
      label: Primary
      color: '#00e6f5'
      type: colour
      enabled: true
    -
      id: m561f5rr
      label: Secondary
      color: '#f700f4'
      type: colour
      enabled: true
    -
      id: m5633lww
      label: Tertiary
      color: '#000000'
      type: colour
      enabled: true
    -
      id: m561g7zz
      label: Quaternary
      color: '#808080'
      type: colour
      enabled: true
    -
      id: m5648nkg
      label: Default
      color: '#ffffff'
      type: colour
      enabled: true
