title: 'Theme Settings'
data:
  primary: '#325ced'
  secondary: '#bccaef'
  tertiary: '#eff4fe'
  quaternary: '#f9f9f9'
  white: '#ffffff'
  lightGrey: '#c8c7cc'
  darkGrey: '#666666'
  black: '#000000'
