tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: colours
            field:
              type: replicator
              display: Colours
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    colour:
                      display: Colour
                      fields:
                        -
                          handle: label
                          field:
                            type: text
                            display: Label
                        -
                          handle: color
                          field:
                            type: color
                            display: Color
